repos:
  - repo: local
    hooks:
      - id: rule-convert
        name: overrid rules convert
        entry: python -X utf8 yaml2js.py --precommit
        language: system
        pass_filenames: false
